"""Add missing columns to hotels and room_types tables

Revision ID: 40267204c380
Revises: e0d02b189252
Create Date: 2026-02-07 18:11:12.192985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40267204c380'
down_revision: Union[str, Sequence[str], None] = 'e0d02b189252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('hotels', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('room_types', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('room_types', sa.Column('capacity', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('room_types', sa.Column('amenities', sa.Text(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'amenities')
    op.drop_column('room_types', 'capacity')
    op.drop_column('room_types', 'description')
    op.drop_column('hotels', 'image_url')
    op.drop_column('hotels', 'rating')
    op.drop_column('hotels', 'description')
    # ### end Alembic commands ###
